### ISSUE TITLE
ES5 compatibility

### ISSUE THREAD

**Issue by digocesar** [sindresorhus/invert-kv#2]
I'm using lcid project that depends on this.
But when I build react + webpack project with this I get error with Uglify because this project is using function declaration implemented in EF6. There is a possibility to use EF5 function declaration type?

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
